package server;

import java.net.MalformedURLException;
import java.net.URL;
import javax.xml.namespace.QName;
import javax.xml.ws.Service;
import javax.xml.ws.WebEndpoint;
import javax.xml.ws.WebServiceClient;
import javax.xml.ws.WebServiceException;
import javax.xml.ws.WebServiceFeature;

import com.webservice.*;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.2.9-b130926.1035
 * Generated source version: 2.2
 */
@WebServiceClient(name = "ProjectServerService", targetNamespace = "http://www.webservice.com", wsdlLocation = "http://127.0.0.1:8001/WebMeeting/ProjectServer?wsdl")
public class ProjectServerService extends Service {

    private final static URL PROJECTSERVERSERVICE_WSDL_LOCATION;
    private final static WebServiceException PROJECTSERVERSERVICE_EXCEPTION;
    private final static QName PROJECTSERVERSERVICE_QNAME = new QName("http://www.webservice.com", "ProjectServerService");

    static {
        URL url = null;
        WebServiceException e = null;
        try {
            url = new URL("http://127.0.0.1:8001/WebMeeting/ProjectServer?wsdl");
        } catch (MalformedURLException ex) {
            e = new WebServiceException(ex);
        }
        PROJECTSERVERSERVICE_WSDL_LOCATION = url;
        PROJECTSERVERSERVICE_EXCEPTION = e;
    }

    public ProjectServerService() {
        super(__getWsdlLocation(), PROJECTSERVERSERVICE_QNAME);
    }

    public ProjectServerService(WebServiceFeature... features) {
        super(__getWsdlLocation(), PROJECTSERVERSERVICE_QNAME, features);
    }

    public ProjectServerService(URL wsdlLocation) {
        super(wsdlLocation, PROJECTSERVERSERVICE_QNAME);
    }

    public ProjectServerService(URL wsdlLocation, WebServiceFeature... features) {
        super(wsdlLocation, PROJECTSERVERSERVICE_QNAME, features);
    }

    public ProjectServerService(URL wsdlLocation, QName serviceName) {
        super(wsdlLocation, serviceName);
    }

    public ProjectServerService(URL wsdlLocation, QName serviceName, WebServiceFeature... features) {
        super(wsdlLocation, serviceName, features);
    }

    /**
     * @return returns Project
     */
    @WebEndpoint(name = "projectPort")
    public Project getProjectPort() {
        return super.getPort(new QName("http://www.webservice.com", "projectPort"), Project.class);
    }

    /**
     * @param features A list of {@link javax.xml.ws.WebServiceFeature} to configure on the proxy.  Supported features not in the <code>features</code> parameter will have their default values.
     * @return returns Project
     */
    @WebEndpoint(name = "projectPort")
    public Project getProjectPort(WebServiceFeature... features) {
        return super.getPort(new QName("http://www.webservice.com", "projectPort"), Project.class, features);
    }

    private static URL __getWsdlLocation() {
        if (PROJECTSERVERSERVICE_EXCEPTION != null) {
            throw PROJECTSERVERSERVICE_EXCEPTION;
        }
        return PROJECTSERVERSERVICE_WSDL_LOCATION;
    }

}