package com.webservice;

import javax.xml.ws.WebFault;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.2.9-b130926.1035
 * Generated source version: 2.2
 */
@WebFault(name = "ParseException", targetNamespace = "http://www.webservice.com")
public class ParseException_Exception extends Exception {

    /**
     * Java type that goes as soapenv:Fault detail element.
     */
    private ParseException faultInfo;

    /**
     * @param faultInfo fault information
     * @param message   message
     */
    public ParseException_Exception(String message, ParseException faultInfo) {
        super(message);
        this.faultInfo = faultInfo;
    }

    /**
     * @param faultInfo fault information
     * @param cause     cause
     * @param message   message
     */
    public ParseException_Exception(String message, ParseException faultInfo, Throwable cause) {
        super(message, cause);
        this.faultInfo = faultInfo;
    }

    /**
     * @return returns fault bean: com.webservice.ParseException
     */
    public ParseException getFaultInfo() {
        return faultInfo;
    }
}