package com.webservice;

import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.ws.Action;
import javax.xml.ws.FaultAction;
import javax.xml.ws.RequestWrapper;
import javax.xml.ws.ResponseWrapper;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.2.9-b130926.1035
 * Generated source version: 2.2
 */
@WebService(name = "project", targetNamespace = "http://www.webservice.com")
@XmlSeeAlso({
        ObjectFactory.class
})

public interface Project {

    /**
     * @param arg0 arg0
     * @return returns boolean
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "removeAll", targetNamespace = "http://www.webservice.com", className = "com.webservice.RemoveAll")
    @ResponseWrapper(localName = "removeAllResponse", targetNamespace = "http://www.webservice.com", className = "com.webservice.RemoveAllResponse")
    @Action(input = "http://www.webservice.com/project/removeAllRequest", output = "http://www.webservice.com/project/removeAllResponse")
    public boolean removeAll(
            @WebParam(name = "arg0", targetNamespace = "")
                    String arg0);

    /**
     * @param arg1 arg1
     * @param arg0 arg0
     * @return returns int
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "login", targetNamespace = "http://www.webservice.com", className = "com.webservice.Login")
    @ResponseWrapper(localName = "loginResponse", targetNamespace = "http://www.webservice.com", className = "com.webservice.LoginResponse")
    @Action(input = "http://www.webservice.com/project/loginRequest", output = "http://www.webservice.com/project/loginResponse")
    public int login(
            @WebParam(name = "arg0", targetNamespace = "")
                    String arg0,
            @WebParam(name = "arg1", targetNamespace = "")
                    String arg1);

    /**
     * @param arg1 arg1
     * @param arg0 arg0
     * @return returns java.lang.String
     * @throws ParseException_Exception ParseException Exception
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "quaryMeeting", targetNamespace = "http://www.webservice.com", className = "com.webservice.QuaryMeeting")
    @ResponseWrapper(localName = "quaryMeetingResponse", targetNamespace = "http://www.webservice.com", className = "com.webservice.QuaryMeetingResponse")
    @Action(input = "http://www.webservice.com/project/quaryMeetingRequest", output = "http://www.webservice.com/project/quaryMeetingResponse", fault = {
            @FaultAction(className = ParseException_Exception.class, value = "http://www.webservice.com/project/quaryMeeting/Fault/ParseException")
    })
    public String quaryMeeting(
            @WebParam(name = "arg0", targetNamespace = "")
                    String arg0,
            @WebParam(name = "arg1", targetNamespace = "")
                    String arg1)
            throws ParseException_Exception;

    /**
     * @param arg3 arg3
     * @param arg2 arg2
     * @param arg1 arg1
     * @param arg0 arg0
     * @return returns int
     * @throws ParseException_Exception ParseException Exception
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "addProjects", targetNamespace = "http://www.webservice.com", className = "com.webservice.AddProjects")
    @ResponseWrapper(localName = "addProjectsResponse", targetNamespace = "http://www.webservice.com", className = "com.webservice.AddProjectsResponse")
    @Action(input = "http://www.webservice.com/project/addProjectsRequest", output = "http://www.webservice.com/project/addProjectsResponse", fault = {
            @FaultAction(className = ParseException_Exception.class, value = "http://www.webservice.com/project/addProjects/Fault/ParseException")
    })
    public int addProjects(
            @WebParam(name = "arg0", targetNamespace = "")
                    String arg0,
            @WebParam(name = "arg1", targetNamespace = "")
                    String arg1,
            @WebParam(name = "arg2", targetNamespace = "")
                    String arg2,
            @WebParam(name = "arg3", targetNamespace = "")
                    String arg3)
            throws ParseException_Exception;

    /**
     * @param arg0 arg0
     * @return returns java.lang.String
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "displayProject", targetNamespace = "http://www.webservice.com", className = "com.webservice.DisplayProject")
    @ResponseWrapper(localName = "displayProjectResponse", targetNamespace = "http://www.webservice.com", className = "com.webservice.DisplayProjectResponse")
    @Action(input = "http://www.webservice.com/project/displayProjectRequest", output = "http://www.webservice.com/project/displayProjectResponse")
    public String displayProject(
            @WebParam(name = "arg0", targetNamespace = "")
                    String arg0);

    /**
     * @param arg1 arg1
     * @param arg0 arg2
     * @return returns int
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "addPerson", targetNamespace = "http://www.webservice.com", className = "com.webservice.AddPerson")
    @ResponseWrapper(localName = "addPersonResponse", targetNamespace = "http://www.webservice.com", className = "com.webservice.AddPersonResponse")
    @Action(input = "http://www.webservice.com/project/addPersonRequest", output = "http://www.webservice.com/project/addPersonResponse")
    public int addPerson(
            @WebParam(name = "arg0", targetNamespace = "")
                    String arg0,
            @WebParam(name = "arg1", targetNamespace = "")
                    String arg1);

    /**
     * @param arg2 arg2
     * @param arg1 arg1
     * @param arg0 arg0
     * @return returns int
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "removeProject", targetNamespace = "http://www.webservice.com", className = "com.webservice.RemoveProject")
    @ResponseWrapper(localName = "removeProjectResponse", targetNamespace = "http://www.webservice.com", className = "com.webservice.RemoveProjectResponse")
    @Action(input = "http://www.webservice.com/project/removeProjectRequest", output = "http://www.webservice.com/project/removeProjectResponse")
    public int removeProject(
            @WebParam(name = "arg0", targetNamespace = "")
                    String arg0,
            @WebParam(name = "arg1", targetNamespace = "")
                    String arg1,
            @WebParam(name = "arg2", targetNamespace = "")
                    String arg2);
}
